const totalMonth = document.querySelector('.total-month');
const totalYear = document.querySelector('.total-year');
const slider1 = document.querySelector('.slider');
const slider2 = document.querySelector('.slider-1');
const box1 = document.getElementById('box1');
const box2 = document.getElementById('box2');
const text = document.querySelector('.text');
const note = document.querySelector('.note');
const noteMobile = document.querySelector('.note-mobile');
const perCent = document.querySelector('.per-cent');
let euro = 83.11;
let booster = Math.ceil(350000 / euro);
let amount = booster;
let upperPerCent = 0;
let fixedPerCent = 9;
let countPerCent = 9;
let total = Math.ceil(amount * 0.01 * countPerCent);
totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
totalYear.innerHTML = `${total.toLocaleString()} €`;
box2.innerHTML = `${(amount).toLocaleString()}`;
const range = () => {
  let val1 = slider1.value;
  let val2 = slider2.value;
  switch(true){
    case val1 == 0:
      fixedPerCent = 7;
      countPerCent = fixedPerCent + upperPerCent;
      perCent.innerHTML = `${countPerCent} %`;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      break;
    case val1 == 1:
      fixedPerCent = 8;
      countPerCent = fixedPerCent + upperPerCent;
      perCent.innerHTML = `${countPerCent} %`;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      break;
    case val1 == 2:
      fixedPerCent = 9;
      countPerCent = fixedPerCent + upperPerCent;
      perCent.innerHTML = `${countPerCent} %`;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      break;
  };
  val1 = val1 * 50;
  switch(true){
    case val2 == 1:
      upperPerCent = 0;
      countPerCent = fixedPerCent + upperPerCent;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      perCent.innerHTML = `${countPerCent} %`;
      box1.innerHTML = `${val2}`;
      box2.innerHTML = `${(val2 * booster).toLocaleString()}`;
      amount = val2 * booster;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      note.style.opacity = '0';
      noteMobile.style.opacity = '0';
      val2 = val2 * 4.9;
      break;
    case val2 <= 11:
      box1.innerHTML = `${val2}`;
      box2.innerHTML = `${(val2 * booster).toLocaleString()}`;
      upperPerCent = Number((0.3 * (val2 - 1)).toFixed(1));
      countPerCent = upperPerCent + fixedPerCent;
      console.log(0.3 + 5);
      perCent.innerHTML = `${countPerCent} %`;
      note.innerHTML = `${upperPerCent}%<br>Increasing<br>rate`;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      note.style.opacity = '1';
      noteMobile.style.opacity = '1';
      noteMobile.innerHTML = `${upperPerCent}% increasing rate`;
      amount = val2 * booster;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      note.style.marginLeft = `${val2*16 - 26}px`;
      val2 = val2 * 4.9;
      break;
    case (val2 > 11) && (val2 < 20):
      box1.innerHTML = `${val2}`;
      box2.innerHTML = `${(val2 * booster).toLocaleString()}`;
      upperPerCent = 3;
      countPerCent = fixedPerCent + upperPerCent;
      perCent.innerHTML = `${countPerCent} %`;
      note.innerHTML = `${upperPerCent}%<br>Increasing<br>rate`;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      note.style.opacity = '1';
      noteMobile.style.opacity = '1';
      noteMobile.innerHTML = `${upperPerCent}% increasing rate`;
      amount = val2 * booster;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      note.style.marginLeft = `${val2*16 - 26}px`;
      val2 = val2 * 4.9;
      break;
    case val2 == 20:
      box1.innerHTML = `${val2}`;
      box2.innerHTML = `${(val2 * booster).toLocaleString()}`;
      upperPerCent = 3;
      countPerCent = fixedPerCent + upperPerCent;
      perCent.innerHTML = `${countPerCent} %`;
      note.innerHTML = `${upperPerCent}%<br>Increasing<br>rate`;
      text.innerHTML = `Standart rate - ${fixedPerCent} %<br>Increasing rate - ${upperPerCent} %`;
      note.style.opacity = '1';
      noteMobile.style.opacity = '1';
      noteMobile.innerHTML = `${upperPerCent}% increasing rate`;
      amount = val2 * booster;
      total = Math.ceil(amount * 0.01 * countPerCent);
      totalMonth.innerHTML = `${Math.ceil(total / 12).toLocaleString()} €`;
      totalYear.innerHTML = `${total.toLocaleString()} €`;
      note.style.marginLeft = `${val2*16 - 26}px`;
      val2 = 100;
      break;
  };
  slider1.style.background = `-webkit-linear-gradient(left ,#FE3D3D 0%,#FE3D3D ${val1}%,#fff ${val1}%, #fff 100%)`;
  slider2.style.background = `-webkit-linear-gradient(left ,#FE3D3D 0%,#FE3D3D ${val2}%,#fff ${val2}%, #fff 100%)`;
 };